
server:
  port: 8084
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zpd00001/springcloud-config
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/